version: 2.1

jobs:
  build_linux:
    machine:
      image: ubuntu-1604:202004-01
    steps:
      - checkout
      - run:
          name: apt
          command: sudo apt-get update && sudo apt-get install -y libglib2.0-dev libsecret-1-dev gnome-keyring dbus-x11
      - run:
          name: install cmake
          command: >
              sudo apt purge --auto-remove cmake &&
              sudo pip install --upgrade cmake
      - run:
          name: dbus
          command: eval "$(dbus-launch --sh-syntax)"
      - run:
          name: mkdir keyring
          command: mkdir -p ~/.cache && mkdir -p ~/.local/share/keyrings
      - run:
          name: unlock keyring
          command: printf '\n' | gnome-keyring-daemon --unlock
      - run:
          name: start keyring daemon
          command: printf '\n' | gnome-keyring-daemon --start
      - run:
          name: Build & Install
          command: sudo make install
      - run:
          name: Run example
          command: make example

  build_mac:
    macos:
      xcode: "11.3.1"
    steps:
      - checkout
      - run:
          name: Install cmake
          command: brew install cmake
      - run:
          name: Build & Install
          command: make install
      - run:
          name: Run example
          command: make example

workflows:
  version: 2
  build:
    jobs:
      - "build_linux"
      - "build_mac"
