version: 2.1

jobs:
  build:
    docker:
      - image: ryangraham/keyring:0.0.1
    steps:
      - checkout
      - run:
          name: Build & Install
          command: make install
      - run:
          name: Run an example
          command: make example
