version: 2.1

jobs:
  build_linux:
    machine:
      image: ubuntu-1604:202004-01
    steps:
      - checkout
      - run:
          name: apt
          command: sudo apt-get update && sudo apt-get install -y libglib2.0-dev libsecret-1-dev gnome-keyring dbus-x11
      - run:
          name: install cmake
          command: >
              sudo apt purge --auto-remove cmake &&
              sudo pip install --upgrade cmake
      - run:
          name: build & install
          command: sudo make install
      - run:
          name: start keyring & run tests
          command: >
              eval "$(dbus-launch --sh-syntax)" &&
              mkdir -p ~/.cache &&
              mkdir -p ~/.local/share/keyrings &&
              eval "$(printf '\n' | gnome-keyring-daemon --unlock)" &&
              eval "$(printf '\n' | /usr/bin/gnome-keyring-daemon --start)" &&
              make example

  build_mac:
    macos:
      xcode: "11.3.1"
    steps:
      - checkout
      - run:
          name: install cmake
          command: brew install cmake
      - run:
          name: build & install
          command: make install
      - run:
          name: run example
          command: make example

workflows:
  version: 2
  build:
    jobs:
      - "build_linux"
      - "build_mac"
