version: 2.1

jobs:
  build_linux:
    docker:
      - image: ryangraham/keyring:0.0.1
    steps:
      - checkout
      - run:
          name: Build & Install
          command: make install
      - run:
          name: Run example
          command: make example

  build_mac:
    macos:
      xcode: "11.3.1"
    steps:
      - checkout
      - run:
          name: Install cmake
          command: brew install cmake
      - run:
          name: Build & Install
          command: make install
      - run:
          name: Run example
          command: make example

workflows:
  version: 2
  build:
    jobs:
      - "build_linux"
      - "build_mac"
